version: "2.0"
services:
  jenkins:
    image: "jenkinsci/blueocean"
    ports:
    - "8080:8080"
    volumes:
    - jenkins_home:/var/jenkins_home
  sonarqube:
    image: sonarqube
    ports:
    - "9000:9000"
    volumes:
    - sonarqube_data:/opt/sonarqube/data
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar

  postgres:
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar

volumes:
  jenkins_home:
  sonarqube_data:
  postgres_data:
